apiVersion: v1
kind: Pod
metadata:
  name: php
  labels:
    name: php
spec:
  containers:
    - name: php
      image: phpmyadmin:latest
      env:
      - name: PMA_HOST
        value: mysql-con
      - name: PMA_PORT
        value: "3306"
      ports:
      - containerPort: 80    