apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: mysql:latest
    env: 
      - name: MYSQL_ROOT_PASSWORD 
        value: "123" 
    ports:
      - containerPort: 3306
